name: Lint & Unit tests & Coverage
on:
  push:
    # branches-ignore: [dev, release, gh-pages]
    branches: [fix/lint-test-action]
jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
          key: node-modules
      - run: npm install
      - name: lint
        run: npm run lint
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
          key: node-modules
      - run: npm install
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      - run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/secrets/google.json" >> $GITHUB_ENV
        shell: bash
      - name: Unit testing of the app with Jest coverage report
        run: npm run test:unit
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}