name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
          key: node-modules
      - run: npm install
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      - run: echo ::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/secrets/google.json
        shell: bash
      - name: unittest
        run: npm run test:unit
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
