# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: npm install
    # Runs a single command using the runners shell
    - name: unittest
      run: npm run test:unit
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install
    - name: Jest Code Coverage Report
      uses: ziishaned/jest-reporter-action@0.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: cross-env NODE_ICU_DATA=node_modules/full-icu vue-cli-service test:unit

