name: Build and Deploy Storybook
on: 
  push:
    branches: [ feature-docs-storybook-new-kouts ]
jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Set email
        run: git config --global user.email "developer-one@pitcher.com"
      - name: Set username
        run: git config --global user.name "Pitcher Developer One"
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs