name: Storybook Build
on:
  push:
    branches: [ feature-docs-storybook-new-kouts ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: npm run build-storybook -o ./docs
        run: npm run build-storybook -o ./docs
      - name: Commit docs folder
        run: |
          git config --local user.email "docs@pitcher.com"
          git config --local user.name "Storybook Committer"
          git add ./docs
          git commit -m "docs builded"
