name: Storybook Build
on:
  push:
    branches: [ feature-docs-storybook-new-kouts ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: npm run build-storybook
        run: npm run build-storybook
      - name: commit & push ./docs folder
            uses: github-actions-x/commit@v2.7
            with:
              github-token: ${{ secrets.REPO_ACCESS }}
              push-branch: 'feature-docs-storybook-new-kouts'
              commit-message: 'publish docs'
              force-add: 'true'
              files: docs/
              name: sdk-docs
              email: sdk-docs@pitcher.com 