name: Storybook Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: npm run build-storybook -o ./docs
        run: npm run build-storybook -o ./docs
