name: Storybook Build
on:
  push:
    branches: [ feature-docs-storybook-new-kouts ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: clear
        run: npm install
      - name: npm install
        run: npm install
      - name: npm run build-storybook
        run: npm run build-storybook
      - name: commit & push ./docs folder
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.REPO_ACCESS }}
          push-branch: 'feature-docs-storybook-new-kouts'
          commit-message: 'publish docs'
          force-add: 'true'
          files: docs/
          name: sdk-docs
          email: sdk-docs@pitcher.com
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
          BRANCH: feature-docs-storybook-new-kouts
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch